// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace dotnetfirstapi.Function.Models
{
    /// <summary> The Sensorefficiency. </summary>
    public partial class Sensorefficiency
    {
        /// <summary> Initializes a new instance of Sensorefficiency. </summary>
        /// <param name="value"> . </param>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        internal Sensorefficiency(string value)
        {
            if (value == null)
            {
                throw new ArgumentNullException(nameof(value));
            }

            Value = value;
        }

        public string Value { get; }
    }
}
